baseURL = 'https://www.tormakristof.eu/'
languageCode = 'en-us'
title = 'LandingPage'
theme = "bootstrap-bp-hugo-startpage"
copyright = "Kristof Torma"
enableRobotsTXT = true
pygmentsCodeFences = true

[Author]  
  name = "Kristof Torma"

[params]
  description = "Have a look!"
  startPageColumns = true
  welcomeText = "Welcome!"

[[params.searchEngines]]
  name = "DuckDuckGo"
  activated = true
  url = "https://duckduckgo.com/"